### ISSUE TITLE
Support for environment variables in Docker steps

### ISSUE THREAD

**Issue by Anthony-Jhoiro** [selflow/selflow#58]
Currently, workflows with container steps can be created using the selflow-daemon. 
These steps support multiple arguments but do not support running with environment variables.

Environment variables can be set directly in the configuration or dynamically using other step's output or metadata.

Selflow Daemon configuration using environment variables in docker steps:
```yaml
name: With Docker environment variables
description: |
  Step C depends on steps B. 
  Step A displays the value od MY_ENV 
  Step B outputs foo=bar and Step C displays the output of step b passed by the STEP_B_OUTPUT environment variable

author: Jhon Doe

workflow:
  timeout: 5m
  steps:
    step-a:
      kind: docker
      with:
        image: node:lts
        environment:
          MY_ENV: my-env-value
        commands: |
          echo "##step-a##"
          echo "$MY_ENV"

    step-b:
      kind: docker
      with:
        image: node:lts
        commands: |
          echo "::output::foo::bar"

    step-c:
      kind: docker
      needs:
        - step-b
      with:
        image: node:lts
        environment:
          STEP_B_OUTPUT: "{{ index .Needs "step-b" "foo" }}"
        commands: |
          echo "##step-c##"
          echo "$STEP_B_OUTPUT"

```
